### ISSUE TITLE
deploy app - 500 Internal server Error on Ngrok

### ISSUE THREAD

**Issue by azzouzze** [Shopify/shopify_app#1020]
folks, i need your kind help. 

i tried many solution but still no luck.
still getting the /auth/callback 500 internal server error in ngrok.
and the shopify server throw a webhook creation error below:
Failed to register webhook {
errors: [
{
message: "Invalid url 'undefined/webhooks/products/create', missing host",
locations: [Array],
path: [Array],
extensions: [Object]
}
]
}
TypeError: Cannot read property 'appSubscriptionCreate' of undefined
at getSubscriptionUrl (/shopify-demo-app/server/getSubscriptionUrl.js:48:45)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async afterAuth (/shopify-demo-app/server.js:57:9)

any help please ? #486

**Comment by azzouzze** [comment]
issue fixed. solution:
env file was missing critical info:
HOST="YOUR_TUNNEL_URL"
SHOP="my-shop-name.myshopify.com"
SCOPES=read_products
