### ISSUE TITLE
Active Storage does not work on models set as session repository by the gem

### ISSUE THREAD

**Issue by damienlethiec** [Shopify/shopify_app#1047]
Hi there,

I am trying to use Active Storage on my Shop model in a Shopify App. The Shop model is the session repository model. Unfortunately, when I try to launch the server or the console, I get a `"method_missing": undefined method `has_many_attached' for Shop (call 'Shop.connection' to establish a connection):Class (NoMethodError)`.

Active Storage works great on other models and works great on the Shop model if I comment `config.session_repository = Shop` in the initializer

Ruby Version: 2.6.5
Rails Version: 6.0.0
Shopify App gem version: 11.7.1

I tried to update the gem to the last version (14.0.0) and changed the config accordingly but it does not solve the bug.

Do you know any workaround?

Thanks a lot

**Comment by tanema** [comment]
I am not really sure why you are getting this error. Do you have a more complete stacktrace? Our does not have any associations. Also you could probably try updating the Gem to the newest to see if it works, you would just jeen to change that config line to `config.shop_session_repository = 'Shop'` and use `include ShopifyApp::ShopSessionStorage` on your shop model as well. If all of this does not work for some reason with active storage, you could also just implement the `store(session, *args)` and `retrieve(id)` and `retrieve_by_shopify_domain(domain)` yourself to satisfy the interface for our storage retrieval.

**Comment by tanema** [comment]
Ah actually, it might me a load-issue? Try also changing your config to `config.session_repository = 'Shop'` instead so that shopify_app will load the Shop model constant when it needs to rather than at application startup

**Comment by damienlethiec** [comment]
Thanks for the answer. Below is a more complete stacktrace. I also tried to update to the latest version without success. It seems the problem is because Shopify App asks for a reference to a model in an initializer (related to this issue: [https://github.com/rails/rails/issues/32933](https://github.com/rails/rails/issues/32933)).

Do you have more doc about you last sentence ? (If all of this does not work for some reason with active storage, you could also just implement the store(session, *args) and retrieve(id) and retrieve_by_shopify_domain(domain) yourself to satisfy the interface for our storage retrieval.)

The stacktrace:

```
/usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `has_many_attached' for Shop (call 'Shop.connection' to establish a connection):Class (NoMethodError)
	from /Users/damienlethiec/code/damienlethiec/ProjetsPros/AventureBio/Consulting/Ensovo/ensapp/app/models/shop.rb:52:in `<class:Shop>'
	from /Users/damienlethiec/code/damienlethiec/ProjetsPros/AventureBio/Consulting/Ensovo/ensapp/app/models/shop.rb:48:in `<main>'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:511:in `block in load_file'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:702:in `new_constants_in'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:510:in `load_file'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:407:in `block in require_or_load'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:40:in `block in load_interlock'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:40:in `load_interlock'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:390:in `require_or_load'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:49:in `block in require_or_load'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `require_or_load'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:545:in `load_missing_constant'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:214:in `const_missing'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/inflector/methods.rb:282:in `const_get'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/inflector/methods.rb:282:in `block in constantize'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/inflector/methods.rb:280:in `each'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/inflector/methods.rb:280:in `inject'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/inflector/methods.rb:280:in `constantize'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/inflector/methods.rb:325:in `safe_constantize'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/core_ext/string/inflections.rb:79:in `safe_constantize'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shopify_app-11.7.1/lib/shopify_app/session/session_repository.rb:30:in `load_storage'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shopify_app-11.7.1/lib/shopify_app/session/session_repository.rb:23:in `storage'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shopify_app-11.7.1/lib/shopify_app/session/session_repository.rb:9:in `storage='
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shopify_app-11.7.1/lib/shopify_app/configuration.rb:57:in `session_repository='
	from /Users/damienlethiec/code/damienlethiec/ProjetsPros/AventureBio/Consulting/Ensovo/ensapp/config/initializers/shopify_app.rb:16:in `block in <main>'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/shopify_app-11.7.1/lib/shopify_app/configuration.rb:82:in `configure'
	from /Users/damienlethiec/code/damienlethiec/ProjetsPros/AventureBio/Consulting/Ensovo/ensapp/config/initializers/shopify_app.rb:5:in `<main>'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:319:in `block in load'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:319:in `load'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.1/lib/rails/engine.rb:667:in `block in load_config_initializer'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/notifications.rb:182:in `instrument'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.1/lib/rails/engine.rb:666:in `load_config_initializer'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.1/lib/rails/engine.rb:624:in `block (2 levels) in <class:Engine>'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.1/lib/rails/engine.rb:623:in `each'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.1/lib/rails/engine.rb:623:in `block in <class:Engine>'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.1/lib/rails/initializable.rb:32:in `run'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.1/lib/rails/initializable.rb:50:in `each'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:415:in `call'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `call'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.1/lib/rails/application.rb:363:in `initialize!'
        from /Users/damienlethiec/code/damienlethiec/ProjetsPros/AventureBio/Consulting/Ensovo/ensapp/config/environment.rb:7:in `<main>'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:106:in `preload'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:157:in `serve'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/rbenv/1.1.2/versions/2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by damienlethiec** [comment]
> Ah actually, it might me a load-issue? Try also changing your config to `config.session_repository = 'Shop'` instead so that shopify_app will load the Shop model constant when it needs to rather than at application startup

Yes, I think you are right. But my config is already like this. Please find it below:

```
# frozen_string_literal: true

require './app/models/shop.rb'

ShopifyApp.configure do |config|
  config.application_name = 'Ensapp'
  config.api_key = Rails.application.credentials.dig(:shopify, :api_key)
  config.secret = Rails.application.credentials.dig(:shopify, :secret)
  config.old_secret = ''
  config.scope = 'read_products, write_products, read_orders, write_orders, read_locations,' \
                 'read_inventory, write_inventory, write_fulfillments, read_fulfillments,' \
                 'read_all_orders'
  config.embedded_app = true
  config.after_authenticate_job = false
  config.api_version = '2019-10'
  config.session_repository = 'Shop'
end

# ShopifyApp::Utils.fetch_known_api_versions
# Uncomment to fetch known api versions from shopify servers on boot
# ShopifyAPI::ApiVersion.version_lookup_mode = :raise_on_unknown
# Uncomment to raise an error if attempting to use an api version that was not previously known
```

**Comment by tanema** [comment]
> I also tried to update to the latest version without success.

What were the problems with the update. Since we are looking at a loading issue it is most likely to be solved by the newest version because the newest version does lazy loading properly to get around rail's newest reloading constraints.

**Comment by damienlethiec** [comment]
It finally worked with 14.0 ! But I had to remove `require './app/models/shop.rb'` from my config. I don't really remember why I added it and hope it won't break anything :/

**Comment by tanema** [comment]
Yes, shopify_app will use rails autoloading features to resolve the Shop constant, you should not require it in your config so that your config can be reloadable in future versions of rails.

**Comment by damienlethiec** [comment]
Thanks so much !
