### ISSUE TITLE
[tests] Intermittently failing tests: undefined method `shopify_app_path'

### ISSUE THREAD

**Issue by andyw8** [Shopify/shopify_app#1218]
I've seen a few builds with this failure, e.g.:

https://github.com/Shopify/shopify_app/pull/1204/checks?check_run_id=2041576868

```
Error:
ShopifyApp::SessionsControllerTest#test_#new_redirects_to_the_enable_cookies_page_if_we_can't_set_cookies_and_the_user_agent_supports_cookie_partitioning:
NoMethodError: undefined method `shopify_app_path' for #<Module:0x00007fabee568398>
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/mapper.rb:687:in `block in define_generate_prefix'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/mapper.rb:699:in `block (2 levels) in define_generate_prefix'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/route_set.rb:807:in `url_for'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/route_set.rb:269:in `call'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/route_set.rb:211:in `call'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/route_set.rb:326:in `block in define_url_helper'
    /Users/runner/work/shopify_app/shopify_app/app/controllers/shopify_app/sessions_controller.rb:146:in `enable_cookie_access'
    /Users/runner/work/shopify_app/shopify_app/app/controllers/shopify_app/sessions_controller.rb:91:in `authenticate_with_partitioning'
    /Users/runner/work/shopify_app/shopify_app/app/controllers/shopify_app/sessions_controller.rb:69:in `authenticate'
    /Users/runner/work/shopify_app/shopify_app/app/controllers/shopify_app/sessions_controller.rb:13:in `new'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/abstract_controller/base.rb:195:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/rendering.rb:30:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:135:in `run_callbacks'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/abstract_controller/callbacks.rb:41:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/rescue.rb:22:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications.rb:180:in `block in instrument'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications.rb:180:in `instrument'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.5/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/abstract_controller/base.rb:136:in `process'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.5/lib/action_view/rendering.rb:39:in `process'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal.rb:190:in `dispatch'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/test_case.rb:517:in `process'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/template_assertions.rb:62:in `process'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/test_case.rb:395:in `get'
    /Users/runner/work/shopify_app/shopify_app/test/controllers/sessions_controller_test.rb:27:in `block in <class:SessionsControllerTest>'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:98:in `block (3 levels) in run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:195:in `capture_exceptions'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:95:in `block (2 levels) in run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:272:in `time_it'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:94:in `block in run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:367:in `on_signal'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:211:in `with_info_handler'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:93:in `run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:1029:in `run_one_method'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:341:in `run_one_method'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:328:in `block (2 levels) in run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:327:in `each'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:327:in `block in run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:367:in `on_signal'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:354:in `with_info_handler'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:326:in `run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/test_unit/line_filtering.rb:10:in `run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:164:in `block in __run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:164:in `map'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:164:in `__run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:141:in `run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:68:in `block in autorun'

rails test /Users/runner/work/shopify_app/shopify_app/test/controllers/sessions_controller_test.rb:24

.........E

Error:
ShopifyApp::SessionsControllerTest#test_#new_sets_the_top_level_oauth_cookie_if_a_valid_shop_param_exists_and_user_agent_supports_cookie_partitioning:
NoMethodError: undefined method `shopify_app_path' for #<Module:0x00007fabee568398>
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/mapper.rb:687:in `block in define_generate_prefix'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/mapper.rb:699:in `block (2 levels) in define_generate_prefix'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/route_set.rb:807:in `url_for'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/route_set.rb:269:in `call'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/route_set.rb:211:in `call'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/route_set.rb:326:in `block in define_url_helper'
    /Users/runner/work/shopify_app/shopify_app/app/controllers/shopify_app/sessions_controller.rb:146:in `enable_cookie_access'
    /Users/runner/work/shopify_app/shopify_app/app/controllers/shopify_app/sessions_controller.rb:91:in `authenticate_with_partitioning'
    /Users/runner/work/shopify_app/shopify_app/app/controllers/shopify_app/sessions_controller.rb:69:in `authenticate'
    /Users/runner/work/shopify_app/shopify_app/app/controllers/shopify_app/sessions_controller.rb:13:in `new'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/abstract_controller/base.rb:195:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/rendering.rb:30:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:135:in `run_callbacks'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/abstract_controller/callbacks.rb:41:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/rescue.rb:22:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications.rb:180:in `block in instrument'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications.rb:180:in `instrument'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.5/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/abstract_controller/base.rb:136:in `process'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.5/lib/action_view/rendering.rb:39:in `process'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal.rb:190:in `dispatch'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/test_case.rb:517:in `process'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/template_assertions.rb:62:in `process'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/test_case.rb:395:in `get'
    /Users/runner/work/shopify_app/shopify_app/test/controllers/sessions_controller_test.rb:96:in `block in <class:SessionsControllerTest>'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:98:in `block (3 levels) in run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:195:in `capture_exceptions'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:95:in `block (2 levels) in run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:272:in `time_it'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:94:in `block in run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:367:in `on_signal'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:211:in `with_info_handler'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:93:in `run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:1029:in `run_one_method'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:341:in `run_one_method'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:328:in `block (2 levels) in run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:327:in `each'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:327:in `block in run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:367:in `on_signal'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:354:in `with_info_handler'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:326:in `run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/test_unit/line_filtering.rb:10:in `run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:164:in `block in __run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:164:in `map'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:164:in `__run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:141:in `run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:68:in `block in autorun'

rails test /Users/runner/work/shopify_app/shopify_app/test/controllers/sessions_controller_test.rb:94

......E

Error:
ShopifyApp::SessionsControllerTest#test_#new_renders_the_request_storage_access_layout_if_we_do_not_have_storage_access:
NoMethodError: undefined method `shopify_app_path' for #<Module:0x00007fabee568398>
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/mapper.rb:687:in `block in define_generate_prefix'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/mapper.rb:699:in `block (2 levels) in define_generate_prefix'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/route_set.rb:807:in `url_for'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/route_set.rb:269:in `call'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/route_set.rb:211:in `call'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_dispatch/routing/route_set.rb:326:in `block in define_url_helper'
    /Users/runner/work/shopify_app/shopify_app/app/controllers/shopify_app/sessions_controller.rb:179:in `redirect_to_request_storage_access'
    /Users/runner/work/shopify_app/shopify_app/app/controllers/shopify_app/sessions_controller.rb:77:in `authenticate_normally'
    /Users/runner/work/shopify_app/shopify_app/app/controllers/shopify_app/sessions_controller.rb:71:in `authenticate'
    /Users/runner/work/shopify_app/shopify_app/app/controllers/shopify_app/sessions_controller.rb:13:in `new'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/abstract_controller/base.rb:195:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/rendering.rb:30:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:135:in `run_callbacks'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/abstract_controller/callbacks.rb:41:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/rescue.rb:22:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications.rb:180:in `block in instrument'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications.rb:180:in `instrument'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.5/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/abstract_controller/base.rb:136:in `process'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.5/lib/action_view/rendering.rb:39:in `process'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/metal.rb:190:in `dispatch'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/test_case.rb:517:in `process'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/rails-controller-testing-1.0.5/lib/rails/controller/testing/template_assertions.rb:62:in `process'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.5/lib/action_controller/test_case.rb:395:in `get'
    /Users/runner/work/shopify_app/shopify_app/test/controllers/sessions_controller_test.rb:33:in `block in <class:SessionsControllerTest>'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:98:in `block (3 levels) in run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:195:in `capture_exceptions'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:95:in `block (2 levels) in run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:272:in `time_it'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:94:in `block in run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:367:in `on_signal'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:211:in `with_info_handler'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest/test.rb:93:in `run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:1029:in `run_one_method'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:341:in `run_one_method'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:328:in `block (2 levels) in run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:327:in `each'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:327:in `block in run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:367:in `on_signal'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:354:in `with_info_handler'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:326:in `run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/test_unit/line_filtering.rb:10:in `run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:164:in `block in __run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:164:in `map'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:164:in `__run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:141:in `run'
    /Users/runner/work/shopify_app/shopify_app/vendor/bundle/ruby/2.7.0/gems/minitest-5.14.4/lib/minitest.rb:68:in `block in autorun'

rails test /Users/runner/work/shopify_app/shopify_app/test/controllers/sessions_controller_test.rb:31
```

**Comment by andyw8** [comment]
Another example: https://github.com/Shopify/shopify_app/pull/1215/checks?check_run_id=2113247852

**Comment by NabeelAhsen** [comment]
We've noticed this for a few weeks now - it's probably worth taking some time out to investigate why!

**Comment by andyw8** [comment]
This can be reproduced with `bundle exec rake test TESTOPTS="--seed=57116"`.

**Comment by NabeelAhsen** [comment]
I don't want to step on any toes here while investigating this. Just want to share my limited findings as well:

The `main_app` helper provided by `Rails::Engine` is of class `ActionDispatch::Routing::RoutesProxy`. 

The following fails intermittently: `main_app.<some_path>`, and it might be worth starting here to understand why the Engine isn't mounting its routes consistently

**Comment by NabeelAhsen** [comment]
#1225 alone was not enough to fix this issue.

See the following failing build: https://github.com/Shopify/shopify_app/pull/1221/checks?check_run_id=2175638755

Turns out that reloading the Rails routes before each invocation of `ShopifyApp::Engine.routes` in each test is sufficient to handle all cases.

**Comment by NabeelAhsen** [comment]
Keeping this open for a little while to gather more evidence that this issue has been fixed by #1227
