### ISSUE TITLE
InvalidAuthenticityToken When installing app on test Store in Chrome

### ISSUE THREAD

**Issue by asecondwill** [Shopify/shopify_app#1286]
When i click to add app to test store I get the error 

`ActionController::InvalidAuthenticityToken`

Chrome 91.0.4472.106 (Official Build) (x86_64). Cookies set to allow all cookies. 

This is on a demo you can recreate the error with. The app is not embedded, does not use a react or anything and is just a regular rails app that implements the shopify_app gem.

https://github.com/asecondwill/shopifydemo3

Logs from boot to error:
```

shopifydemo3 git:master ❯ rails s
=> Booting Puma
=> Rails 6.1.3.2 application starting in development 
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.3.2 (ruby 2.7.2-p137) ("Sweetnighter")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 89227
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
Started GET "/shopify/splash?hmac=839804d0f67f8d1d82ad1bbadf2ba9a4ad7f69a491e64af4fe984768a077d845&shop=willtest3.myshopify.com&timestamp=1623857382" for 88.97.13.38 at 2021-06-16 16:29:42 +0100
Cannot render console from 88.97.13.38! Allowed networks: 127.0.0.0/127.255.255.255, ::1
   (43.0ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by Shopify::SplashController#splash as HTML
  Parameters: {"hmac"=>"839804d0f67f8d1d82ad1bbadf2ba9a4ad7f69a491e64af4fe984768a077d845", "shop"=>"willtest3.myshopify.com", "timestamp"=>"1623857382"}
  Shop Load (0.9ms)  SELECT "shops".* FROM "shops" WHERE "shops"."shopify_domain" = $1 LIMIT $2  [["shopify_domain", "willtest3.myshopify.com"], ["LIMIT", 1]]
Redirected to https://xxx.ngrok.io/shopify/login?shop=willtest3.myshopify.com&return_to=%2Fshopify%2Fsplash%3Fhmac%3D839804d0f67f8d1d82ad1bbadf2ba9a4ad7f69a491e64af4fe984768a077d845%26shop%3Dwilltest3.myshopify.com%26timestamp%3D1623857382
Filter chain halted as :check_shop_known rendered or redirected
Completed 302 Found in 14ms (ActiveRecord: 3.5ms | Allocations: 3753)


Started GET "/shopify/login?shop=willtest3.myshopify.com&return_to=%2Fshopify%2Fsplash%3Fhmac%3D839804d0f67f8d1d82ad1bbadf2ba9a4ad7f69a491e64af4fe984768a077d845%26shop%3Dwilltest3.myshopify.com%26timestamp%3D1623857382" for 88.97.13.38 at 2021-06-16 16:29:43 +0100
Cannot render console from 88.97.13.38! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by ShopifyApp::SessionsController#new as HTML
  Parameters: {"shop"=>"willtest3.myshopify.com", "return_to"=>"/shopify/splash?hmac=839804d0f67f8d1d82ad1bbadf2ba9a4ad7f69a491e64af4fe984768a077d845&shop=willtest3.myshopify.com&timestamp=1623857382"}
  Rendering /Users/will/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/shopify_app-18.0.1/app/views/shopify_app/shared/post_redirect_to_auth_shopify.html.erb
  Rendered /Users/will/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/shopify_app-18.0.1/app/views/shopify_app/shared/post_redirect_to_auth_shopify.html.erb (Duration: 18.1ms | Allocations: 9056)
Completed 200 OK in 22ms (Views: 21.1ms | ActiveRecord: 0.0ms | Allocations: 10573)


Started POST "/auth/shopify" for 88.97.13.38 at 2021-06-16 16:29:43 +0100
Cannot render console from 88.97.13.38! Allowed networks: 127.0.0.0/127.255.255.255, ::1
D, [2021-06-16T16:29:43.591192 #89227] DEBUG -- omniauth: (shopify) Setup endpoint detected, running now.
D, [2021-06-16T16:29:43.591429 #89227] DEBUG -- omniauth: (shopify) Request phase initiated.
E, [2021-06-16T16:29:43.591902 #89227] ERROR -- omniauth: (shopify) Authentication failure! ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken, ActionController::InvalidAuthenticityToken
  
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
  
omniauth-rails_csrf_protection (1.0.0) lib/omniauth/rails_csrf_protection/token_verifier.rb:34:in `call'
omniauth (2.0.4) lib/omniauth/strategy.rb:240:in `request_call'
omniauth (2.0.4) lib/omniauth/strategy.rb:193:in `call!'
omniauth (2.0.4) lib/omniauth/strategy.rb:169:in `call'
omniauth (2.0.4) lib/omniauth/builder.rb:45:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.1.3.2) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
actionpack (6.1.3.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/cookies.rb:689:in `call'
activerecord (6.1.3.2) lib/active_record/migration.rb:601:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.3.2) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:19:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.3.2) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.3.2) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.3.2) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.3.2) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
shopify_app (18.0.1) lib/shopify_app/middleware/jwt_middleware.rb:23:in `call_next'
shopify_app (18.0.1) lib/shopify_app/middleware/jwt_middleware.rb:11:in `call'
shopify_app (18.0.1) lib/shopify_app/middleware/same_site_cookie_middleware.rb:11:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
rack-mini-profiler (2.3.2) lib/mini_profiler/profiler.rb:384:in `call'
webpacker (5.4.0) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.7.0) lib/rack/proxy.rb:63:in `call'
railties (6.1.3.2) lib/rails/engine.rb:539:in `call'
puma (5.3.2) lib/puma/configuration.rb:249:in `call'
puma (5.3.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.3.2) lib/puma/thread_pool.rb:338:in `with_force_shutdown'
puma (5.3.2) lib/puma/request.rb:76:in `handle_request'
puma (5.3.2) lib/puma/server.rb:438:in `process_client'
puma (5.3.2) lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

**Comment by sayduck-daniel** [comment]
Same here.

**Comment by khoimm92** [comment]
If you use Nginx proxy, follow this guide https://stackoverflow.com/a/57182441/3157257

**Comment by Fivell** [comment]
@asecondwill did you manage to make it work ?

**Comment by WagnerMatos** [comment]
Does anyone have any news on this?

**Comment by daniel-gato** [comment]
Something?

**Comment by lggg123** [comment]
Same here. Any update on how to fix this?

**Comment by janklimo** [comment]
Same here. I wish the issues got resolved instead of being marked stale.
