### ISSUE TITLE
Parameter 'handler': Expected type T.nilable(ShopifyAPI::Webhooks::Handler), got type Class with value OrdersCreateJob (TypeError)

### ISSUE THREAD

**Issue by vfonic** [Shopify/shopify_app#1453]
### Description

I got this Sorbet type error when I tried to setup a webhook for my Shopify app.

### Steps to Reproduce

(steps 1-5 copied from https://github.com/Shopify/shopify_app/issues/1452)

1. `rails new missing_shopify_webhook`
2. `cd missing_shopify_webhook
3. `bundle add shopify_app`
4. `rails generate shopify_app`
5. Add `config.webhooks = [{ topic: 'orders/create', address: 'https://example.com/webhooks/order_created' }]` to `config/initializers/shopify_app.rb`
6. Create `OrdersCreateJob` class in `app/jobs/orders_create_job.rb`
7. `rails s`

**Expected behavior:**

Rails server starts

**Actual behavior:**

<details><summary>What actually happens</summary>

```
....../gems/ruby-3.1.1/gems/sorbet-runtime-0.5.10092/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Parameter 'handler': Expected type T.nilable(ShopifyAPI::Webhooks::Handler), got type Class with value OrdersCreateJob (TypeError)
Caller: ....../gems/ruby-3.1.1/gems/sorbet-runtime-0.5.10092/lib/types/private/methods/call_validation.rb:117
Definition: ....../gems/ruby-3.1.1/gems/shopify_api-10.1.0/lib/shopify_api/webhooks/registry.rb:18
        from ....../gems/ruby-3.1.1/gems/sorbet-runtime-0.5.10092/lib/types/configuration.rb:303:in `call_validation_error_handler'
        from ....../gems/ruby-3.1.1/gems/sorbet-runtime-0.5.10092/lib/types/private/methods/call_validation.rb:191:in `report_error'
        from ....../gems/ruby-3.1.1/gems/sorbet-runtime-0.5.10092/lib/types/private/methods/call_validation.rb:120:in `block in validate_call'
        from ....../gems/ruby-3.1.1/gems/sorbet-runtime-0.5.10092/lib/types/private/methods/signature.rb:211:in `block in each_args_value_type'
        from ....../gems/ruby-3.1.1/gems/sorbet-runtime-0.5.10092/lib/types/private/methods/signature.rb:206:in `each'
        from ....../gems/ruby-3.1.1/gems/sorbet-runtime-0.5.10092/lib/types/private/methods/signature.rb:206:in `each_args_value_type'
        from ....../gems/ruby-3.1.1/gems/sorbet-runtime-0.5.10092/lib/types/private/methods/call_validation.rb:117:in `validate_call'
        from ....../gems/ruby-3.1.1/gems/sorbet-runtime-0.5.10092/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
        from ....../gems/ruby-3.1.1/gems/shopify_app-19.0.2/lib/shopify_app/managers/webhooks_manager.rb:39:in `block in add_registrations'
        from ....../gems/ruby-3.1.1/gems/shopify_app-19.0.2/lib/shopify_app/managers/webhooks_manager.rb:38:in `each'
        from ....../gems/ruby-3.1.1/gems/shopify_app-19.0.2/lib/shopify_app/managers/webhooks_manager.rb:38:in `add_registrations'
        from <the_actual_absolute_path_to_the_app_root>/config/initializers/shopify_app.rb:35:in `block in <main>'
        from ....../gems/ruby-3.1.1/gems/activesupport-7.0.3/lib/active_support/lazy_load_hooks.rb:79:in `block in execute_hook'
        from ....../gems/ruby-3.1.1/gems/activesupport-7.0.3/lib/active_support/lazy_load_hooks.rb:72:in `with_execution_control'
        from ....../gems/ruby-3.1.1/gems/activesupport-7.0.3/lib/active_support/lazy_load_hooks.rb:77:in `execute_hook'
        from ....../gems/ruby-3.1.1/gems/activesupport-7.0.3/lib/active_support/lazy_load_hooks.rb:63:in `block in run_load_hooks'
        from ....../gems/ruby-3.1.1/gems/activesupport-7.0.3/lib/active_support/lazy_load_hooks.rb:62:in `each'
        from ....../gems/ruby-3.1.1/gems/activesupport-7.0.3/lib/active_support/lazy_load_hooks.rb:62:in `run_load_hooks'
        from ....../gems/ruby-3.1.1/gems/railties-7.0.3/lib/rails/application/finisher.rb:87:in `block in <module:Finisher>'
        from ....../gems/ruby-3.1.1/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `instance_exec'
        from ....../gems/ruby-3.1.1/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `run'
        from ....../gems/ruby-3.1.1/gems/railties-7.0.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        from ....../rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
        from ....../rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from ....../rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from ....../rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from ....../rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:347:in `each'
        from ....../rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:347:in `call'
        from ....../rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
        from ....../rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
        from ....../rubies/ruby-3.1.1/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
        from ....../gems/ruby-3.1.1/gems/railties-7.0.3/lib/rails/initializable.rb:60:in `run_initializers'
        from ....../gems/ruby-3.1.1/gems/railties-7.0.3/lib/rails/application.rb:372:in `initialize!'
        from <the_actual_absolute_path_to_the_app_root>/config/environment.rb:5:in `<main>'
        from ....../gems/ruby-3.1.1/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from ....../gems/ruby-3.1.1/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from ....../gems/ruby-3.1.1/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from ....../gems/ruby-3.1.1/gems/railties-7.0.3/lib/rails/application.rb:348:in `require_environment!'
        from ....../gems/ruby-3.1.1/gems/railties-7.0.3/lib/rails/command/actions.rb:28:in `require_environment!'
        from ....../gems/ruby-3.1.1/gems/railties-7.0.3/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        from ....../gems/ruby-3.1.1/gems/railties-7.0.3/lib/rails/commands/console/console_command.rb:101:in `perform'
        from ....../gems/ruby-3.1.1/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from ....../gems/ruby-3.1.1/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from ....../gems/ruby-3.1.1/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from ....../gems/ruby-3.1.1/gems/railties-7.0.3/lib/rails/command/base.rb:87:in `perform'
        from ....../gems/ruby-3.1.1/gems/railties-7.0.3/lib/rails/command.rb:48:in `invoke'
        from ....../gems/ruby-3.1.1/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<main>'
        from ....../gems/ruby-3.1.1/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from ....../gems/ruby-3.1.1/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
```
        </details>

**Reproduces how often:**

Always

### Gem versions

shopify_app 19.0.2
shopify_api 10.1.0

**Comment by yogodoshi** [comment]
Still hasn't been fixed, just happened using version 21.5
