### ISSUE TITLE
Not working ShopifyApp::WebhookManager.recreate_webhooks!

### ISSUE THREAD

**Issue by m11o** [Shopify/shopify_app#1568]
### Description

When I executed ShopifyApp::WebhookManager.recreate_webhooks! to re-register webhooks, it occurred below error.

```ruby
session = ShopifyAPI::Auth::Session.new(shop: 'example.myshopify.com', access_token: 'access_token')
ShopifyApp::WebhooksManager.recreate_webhooks!(session: session)
```

```
ArgumentError (missing keyword: :session):
/vendor/bundle/ruby/2.7.0/gems/shopify_api-12.2.1/lib/shopify_api/webhooks/registry.rb:99:in `unregister'
/vendor/bundle/ruby/2.7.0/gems/sorbet-runtime-0.5.10324/lib/types/private/methods/call_validation.rb:157:in `bind_call'
/vendor/bundle/ruby/2.7.0/gems/sorbet-runtime-0.5.10324/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/vendor/bundle/ruby/2.7.0/gems/sorbet-runtime-0.5.10324/lib/types/private/methods/call_validation.rb:89:in `block in create_validator_slow'
/vendor/bundle/ruby/2.7.0/gems/shopify_app-21.1.1/lib/shopify_app/managers/webhooks_manager.rb:33:in `block in destroy_webhooks'
/vendor/bundle/ruby/2.7.0/gems/shopify_app-21.1.1/lib/shopify_app/managers/webhooks_manager.rb:32:in `each'
/vendor/bundle/ruby/2.7.0/gems/shopify_app-21.1.1/lib/shopify_app/managers/webhooks_manager.rb:32:in `destroy_webhooks'
/vendor/bundle/ruby/2.7.0/gems/shopify_app-21.1.1/lib/shopify_app/managers/webhooks_manager.rb:22:in `recreate_webhooks!'
```

Maybe, because [ShopifyAPI::Webhooks::Registry.unregister](https://github.com/Shopify/shopify-api-ruby/blob/0e47580f535b900dd5deb49c30469a4c517cfc75/lib/shopify_api/webhooks/registry.rb#L99) isn't passed `session` arguments in [ShopifyApp::WebhookManager.destroy_webhooks](https://github.com/Shopify/shopify_app/blob/30f14ff3b0f653eb011f8f2558d69b440e5d9326/lib/shopify_app/managers/webhooks_manager.rb#L29-L35).

### Steps to Reproduce

1. Run ShopifyApp::WebhookManager.recreate_webhooks!

**Expected behavior:**

`ShopifyAPI::Webhooks::Registry.unregister`, `webhookSubscriptionDelete`, and `webhookSubscriptionCreate` should be able to be executed when running ShopifyApp::WebhookManager.recreate_webhooks!

**Actual behavior:**

The above error occurred when running ShopifyApp::WebhookManager.recreate_webhooks!

**Reproduces how often:**

### Browsers

Google Chrome 107.0.5304.87 (arm64)

### Gem versions

shopify_app: 21.1.1
shopify_api: 12.2.1

### Security

- [x] I have redacted any private information from my logs or code snippets.

**Comment by m11o** [comment]
Fix: #1569
