### ISSUE TITLE
Webhook registration with fields attribute causes sorbet validation error

### ISSUE THREAD

**Issue by MariaEshopGuide** [Shopify/shopify_app#1632]
# Issue summary

I'm getting an sorbet validation error, when I try to filter the webhook data as described in the manual:

https://github.com/Shopify/shopify_app/blob/v20.2.0/docs/shopify_app/webhooks.md requires
```
ShopifyApp.configure do |config|
  config.webhooks = [
    {topic: 'products/update', path: 'webhooks/products_update', fields: ['title', 'vendor']}
  ]
end
```

My Code: 
```
ShopifyApp.configure do |config|
  config.webhooks = [
    { topic: 'app/uninstalled', path: 'webhooks/app_uninstalled', fields: ['id', 'domain'] }
  ]
end
```

- `shopify_api` version: 11.1.0
- `shopify_app` version: >= 20.2.0
- Ruby version: 3.1.2
- Operating system: Linux/Ubuntu 22.04.1 LTS

## Actual behavior

When I start the websever im getting the error: 

```
/home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10601/lib/types/configuration.rb:296:in `call_validation_error_handler_default': Parameter 'fields': Expected type T.nilable(String), got type Array with value ["id", "domain", "customer_id"] (TypeError)
Caller: /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10601/lib/types/private/methods/call_validation.rb:201
Definition: /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify_api-11.1.0/lib/shopify_api/webhooks/registry.rb:18
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10601/lib/types/configuration.rb:303:in `call_validation_error_handler'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10601/lib/types/private/methods/call_validation.rb:286:in `report_error'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10601/lib/types/private/methods/call_validation.rb:204:in `block in validate_call'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10601/lib/types/private/methods/signature.rb:211:in `block in each_args_value_type'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10601/lib/types/private/methods/signature.rb:206:in `each'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10601/lib/types/private/methods/signature.rb:206:in `each_args_value_type'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10601/lib/types/private/methods/call_validation.rb:201:in `validate_call'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10601/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify_app-20.2.0/lib/shopify_app/managers/webhooks_manager.rb:43:in `block in add_registrations'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify_app-20.2.0/lib/shopify_app/managers/webhooks_manager.rb:40:in `each'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify_app-20.2.0/lib/shopify_app/managers/webhooks_manager.rb:40:in `add_registrations'
	from /path/to/project/config/initializers/shopify_app.rb:43:in `block in <main>'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:92:in `block in execute_hook'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:76:in `block in run_load_hooks'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:75:in `each'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:75:in `run_load_hooks'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/application/finisher.rb:87:in `block in <module:Finisher>'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `run'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/application.rb:372:in `initialize!'
	from /path/to/project/config/environment.rb:5:in `<main>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.5/lib/rack/builder.rb:116:in `eval'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.5/lib/rack/builder.rb:116:in `new_from_string'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.5/lib/rack/builder.rb:105:in `load_file'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.5/lib/rack/builder.rb:66:in `parse_file'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.5/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.5/lib/rack/server.rb:249:in `app'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.5/lib/rack/server.rb:422:in `wrapped_app'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:36:in `start'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:143:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/path//.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /path/to/project/bin/rails:4:in `<main>'

```

## Additional Note

When I use a String instead of an Array ```..., fields: 'domain' }``` as requested by sorbet, the webhook is executed without errors but the transmitted data is not filtered.

## Steps to reproduce the problem

1. rails new test_shopify_webhook && cd test_shopify_webhook
2. bundle add shopify_app
3. rails generate shopify_app
4. Add config.webhooks = [{ topic: 'app/uninstalled', path: 'webhooks/app_uninstalled', fields: ['id', 'domain'] }] to config/initializers/shopify_app.rb
5. rails s

**Comment by MariaEshopGuide** [comment]
Issue (partially) solved. It is indeed possible to restrict the fields via a list of strings: 

```
config.webhooks = [
    { topic: 'orders/create', path: 'webhooks/orders_create', fields:  'id, customer'}
  ]
```

What I haven't found a solution for so far is to restrict nested attributes. With the above solution I get all the information about the customer every time. But actually I only need the id of the customer at this point. I am glad about tips.

**Comment by nelsonwittwer** [comment]
Looks like you figured out the fix here. The API is expecting a comma delimited string of fields as demonstrated [in this unit test](https://github.com/Shopify/shopify-api-ruby/blob/main/test/webhooks/registry_test.rb#L94)

I'm not seeing a way to return a subset of customer information like you are looking for. I'd only persist information you were interested and let the rest of the event get ignored.

Closing as it seems like the correct interface has been determined.
