### ISSUE TITLE
Webhook registration for app uninstalled does not work and leads to  `webhook_job_klass': ShopifyApp::MissingWebhookJobError (ShopifyApp::MissingWebhookJobError)

### ISSUE THREAD

**Issue by Kurbm** [Shopify/shopify_app#1638]
# Issue summary

If I start my server or try to run "rails g shopify_app:add_webhook --topic app/uninstalled --path webhooks/app_uninstalled"

I receive the the error 

../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify_app-21.4.0/lib/shopify_app/managers/webhooks_manager.rb:77:in `webhook_job_klass': ShopifyApp::MissingWebhookJobError (ShopifyApp::MissingWebhookJobError)

I have added the config to the shopify_app.rb initializer

ShopifyApp.configure do |config|
  config.webhooks = [
    { topic: 'app/uninstalled', path: "#{ENV['HOST_URL']}/webhooks/app_uninstalled", format: 'json' }
  ]
end

But I'm not able to get it run.

- `shopify_api` version: 12.4
- `shopify_app` version: 21.4
- Ruby version: 3.1.2
- Operating system: MacOs Ventura 13.0.1

## Actual behavior

```
/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify_app-21.4.0/lib/shopify_app/managers/webhooks_manager.rb:77:in `webhook_job_klass': ShopifyApp::MissingWebhookJobError (ShopifyApp::MissingWebhookJobError)
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify_app-21.4.0/lib/shopify_app/managers/webhooks_manager.rb:53:in `block in add_registrations'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify_app-21.4.0/lib/shopify_app/managers/webhooks_manager.rb:46:in `each'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify_app-21.4.0/lib/shopify_app/managers/webhooks_manager.rb:46:in `add_registrations'
	from /Users/kvn/shopify-apps/easy-html-sitemaps/config/initializers/shopify_app.rb:40:in `block in <main>'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:92:in `block in execute_hook'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:76:in `block in run_load_hooks'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:75:in `each'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.4/lib/active_support/lazy_load_hooks.rb:75:in `run_load_hooks'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/application/finisher.rb:87:in `block in <module:Finisher>'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `run'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/application.rb:372:in `initialize!'
	from /Users/kvn/shopify-apps/easy-html-sitemaps/config/environment.rb:5:in `<main>'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.4/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/application.rb:348:in `require_environment!'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/command/actions.rb:28:in `require_environment!'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/kvn/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from ./bin/rails:4:in `<main>'
```
## Steps to reproduce the problem

1. rails new test_shopify_webhook && cd test_shopify_webhook
2. bundle add shopify_app
3. rails generate shopify_app
4. Add config.webhooks = [{ topic: 'app/uninstalled', path: "#{ENV['HOST_URL']}/webhooks/app_uninstalled", format: 'json' }] to config/initializers/shopify_app.rb
5. rails s or rails g shopify_app:add_webhook --topic app/uninstalled --path webhooks/app_uninstalled

**Comment by gnumarcelo** [comment]
I'm a new user of the `shopify_app` gem but, out of curiosity, is there any particularity that requires you to register the webhook with `ENV['HOST_URL']`? If I'm not mistaken, you should register it with something like:

`{ topic: "app/uninstalled", address: "webhooks/app_uninstalled"}`

Then, you have to place the `AppUninstalledJob` inside `app/jobs/app_uninstalled_job.rb` and everything should work correctly.

**Comment by Kurbm** [comment]
@gnumarcelo, thanks for the hint. Helped indeed.

I have added the examples from the Shopify CLI Rails app.

So for everyone, who looks for proper job:

Add:

```
config.webhooks = [
    # After a store owner uninstalls your app, Shopify invokes the APP_UNINSTALLED webhook
    # to let your app know.
    { topic: "app/uninstalled", address: "api/webhooks/app_uninstalled" },
  ]
 ```
  Inside ShopifyApp.configure in shopify_app.rb

Create a new job with `bin/rails generate job app_uninstalled`

And add the following code in the job : app/jobs/app_uninstalled_job.rb

```
# frozen_string_literal: true

class AppUninstalledJob < ActiveJob::Base
  extend ShopifyAPI::Webhooks::Handler

  class << self
    def handle(topic:, shop:, body:)
      perform_later(topic: topic, shop_domain: shop, webhook: body)
    end
  end

  def perform(topic:, shop_domain:, webhook:)
    shop = Shop.find_by(shopify_domain: shop_domain)

    if shop.nil?
      logger.error("#{self.class} failed: cannot find shop with domain '#{shop_domain}'")
      return
    end

    logger.info("#{self.class} started for shop '#{shop_domain}'")
    shop.destroy
  end
end
```
