### ISSUE TITLE
recreate_webhooks! fails to recreate webhooks as it tries to create mandatory webhooks using the API

### ISSUE THREAD

**Issue by sagar-ranglani** [Shopify/shopify_app#1659]
# Issue summary
Can't use recreate_webhooks! as it tries to create mandatory webhooks using API and I guess that's now allowed!

- `shopify_api` version: 12.4.0
- `shopify_app` version: 21.4.0
- Ruby version: 3.0.2
- Operating system: Mac (Trying this in dev)

```
gems/shopify_api-12.4.0/lib/shopify_api/webhooks/registry.rb:154:in `get_webhook_id': Failed to fetch webhook from Shopify: Argument 'topics' on Field 'webhookSubscriptions' has an invalid value (SHOP_REDACT). Expected type '[WebhookSubscriptionTopic!]'. (ShopifyAPI::Errors::WebhookRegistrationError)
```

## Expected behavior

It should recreate all the webhooks! (I guess, by trying to recreate only the non-mandatory ones)

## Actual behavior

It fails with an error

## Steps to reproduce the problem
1. Try the following in the Rails console

```
irb> ShopifyApp.configuration.has_webhooks?
=> true
irb> ShopifyApp.configuration.webhooks
=>
[{:topic=>"app/uninstalled", :address=>"api/webhooks/app_uninstalled"},
 {:topic=>"orders/fulfilled", :address=>"api/webhooks/orders_fulfilled"},
 {:topic=>"bulk_operations/finish", :address=>"api/webhooks/bulk_operations_finish"},
 {:topic=>"orders/create", :address=>"api/webhooks/orders_create"},
 {:topic=>"app_subscriptions/update", :address=>"api/webhooks/app_subscriptions_update"},
 {:topic=>"shop/redact", :address=>"api/webhooks/shop_redact"},
 {:topic=>"customers/redact", :address=>"api/webhooks/customers_redact"},
 {:topic=>"customers/data_request", :address=>"api/webhooks/customers_data_request"}]

irb> shop = Shop.find_by(shopify_domain: 'xxx.myshopify.com')
=>
#<Shop:0x000000010b53bec8
irb> session = ShopifyAPI::Auth::Session.new(shop: shop.shopify_domain, access_token
: shop.shopify_token)
=>
#<ShopifyAPI::Auth::Session:0x0000000109598080
...
irb> ShopifyApp::WebhooksManager.recreate_webhooks!(session: session)
/Users/xxx/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/shopify_api-12.4.0/lib/shopify_api/webhooks/registry.rb:154:in `get_webhook_id': Failed to fetch webhook from Shopify: Argument 'topics' on Field 'webhookSubscriptions' has an invalid value (SHOP_REDACT). Expected type '[WebhookSubscriptionTopic!]'. (ShopifyAPI::Errors::WebhookRegistrationError)

```

**Comment by sagar-ranglani** [comment]
@awd Could you please help me understand what could a simpler workaround here?

**Comment by m11o** [comment]
> So, How about mandatory webhooks should be removed from shopify_app generators in order to avoid confusion like us?

It was wrong.
Mandatory webhook configures made by shopify_app initial generator are necessary when receiving these webhooks. So, we need to modify [ShopifyAPI::Webhooks::Registry#register](https://github.com/Shopify/shopify-api-ruby/blob/2b20d9bd8fb5f58c9f7a8079e1aeb6e12cefd832/lib/shopify_api/webhooks/registry.rb#L47).

**Comment by nelsonwittwer** [comment]
Should be fixed with [this app gem PR](https://github.com/Shopify/shopify_app/pull/1686)
