### ISSUE TITLE
ShopifySessionRepository.shop_storage is not configured!

### ISSUE THREAD

**Issue by CaioFML** [Shopify/shopify_app#1701]
# Issue summary

I'm upgrading shopify_app and shopify_api from 18.1.3 and 9.4.1, respectively, to the newest versions, but I keep getting the error in the screenshot, seems that the options that I'm passing to the shopify_app.rb initializer to find my session_storage as my Shop model does not work

![image](https://github.com/Shopify/shopify_app/assets/37879125/a3021b1b-7035-417e-bd79-ed02d5ca9941)

- `shopify_api` version: 12.5
- `shopify_app` version: 13.0
- Ruby version: 3.0.4
- Operating system: Mac OS Ventura 13.2.1 (M1)

`shopify_app.rb`

```ruby
Rails.application.config.after_initialize do
  if ShopifyApp.configuration.api_key.present? && ShopifyApp.configuration.secret.present?
    ShopifyAPI::Context.setup(
      api_key: ENV.fetch('SHOPIFY_API_KEY', '').presence,
      api_secret_key: ENV.fetch('SHOPIFY_API_SECRET', '').presence,
      api_version: '2022-10',
      host_name: URI(ENV.fetch('HOST', '')).host || '',
      scope: 'read_orders,read_script_tags,write_script_tags,read_products,read_product_listings,read_inventory,read_discounts,read_customers,read_themes,write_themes,write_pixels,read_customer_events,read_price_rules,read_discounts',
      is_private: !ENV.fetch('SHOPIFY_APP_PRIVATE_SHOP', '').empty?,
      is_embedded: true,
      session_storage: ShopifyApp::SessionRepository,
      logger: Rails.logger,
      private_shop: ENV.fetch('SHOPIFY_APP_PRIVATE_SHOP', nil),
      user_agent_prefix: "ShopifyApp/#{ShopifyApp::VERSION}"
    )

    ShopifyApp::WebhooksManager.add_registrations
  end
end
```

I tried with "Shop" instead of `ShopifyApp::SessionRepository` too, didn't find anything related to only that, any thoughts?

## Expected behavior

Don't raise an error and find my Shop model as my session storage during the OAuth process

## Actual behavior

It raises an error `ShopifySessionRepository.shop_storage is not configured!`

## Steps to reproduce the problem

1. I use the shopify dev to install my app in my dev shop and the error occurs during the Oauth process

logs:

```
17:13:34 web.1    | ShopifyApp::ConfigurationError (ShopifySessionRepository.shop_storage is not configured!):
17:13:34 web.1    |   
17:13:34 web.1    | shopify_app (21.5.0) lib/shopify_app/session/session_repository.rb:35:in `shop_storage'
17:13:34 web.1    | shopify_app (21.5.0) lib/shopify_app/session/session_repository.rb:19:in `retrieve_shop_session_by_shopify_domain'
17:13:34 web.1    | shopify_app (21.5.0) app/controllers/concerns/shopify_app/ensure_installed.rb:35:in `installed_shop_session'
17:13:34 web.1    | shopify_app (21.5.0) app/controllers/concerns/shopify_app/ensure_installed.rb:45:in `check_shop_known'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/callbacks.rb:427:in `block in make_lambda'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
17:13:34 web.1    | actionpack (6.1.4.7) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/callbacks.rb:199:in `block in halting'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/callbacks.rb:512:in `block in invoke_before'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/callbacks.rb:512:in `each'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/callbacks.rb:512:in `invoke_before'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/callbacks.rb:115:in `block in run_callbacks'
17:13:34 web.1    | actiontext (6.1.4.7) lib/action_text/rendering.rb:20:in `with_renderer'
17:13:34 web.1    | actiontext (6.1.4.7) lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/callbacks.rb:126:in `instance_exec'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/callbacks.rb:137:in `run_callbacks'
17:13:34 web.1    | actionpack (6.1.4.7) lib/abstract_controller/callbacks.rb:41:in `process_action'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_controller/metal/rescue.rb:22:in `process_action'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/notifications.rb:203:in `block in instrument'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/notifications.rb:203:in `instrument'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
17:13:34 web.1    | activerecord (6.1.4.7) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
17:13:34 web.1    | actionpack (6.1.4.7) lib/abstract_controller/base.rb:165:in `process'
17:13:34 web.1    | actionview (6.1.4.7) lib/action_view/rendering.rb:39:in `process'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_controller/metal.rb:190:in `dispatch'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_controller/metal.rb:254:in `dispatch'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/routing/route_set.rb:33:in `serve'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/journey/router.rb:50:in `block in serve'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/journey/router.rb:32:in `each'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/journey/router.rb:32:in `serve'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/routing/route_set.rb:842:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/rack/browser_monitoring.rb:38:in `traced_call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
17:13:34 web.1    | warden (1.2.9) lib/warden/manager.rb:34:in `catch'
17:13:34 web.1    | warden (1.2.9) lib/warden/manager.rb:34:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | rack (2.2.7) lib/rack/tempfile_reaper.rb:15:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | rack (2.2.7) lib/rack/etag.rb:27:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | rack (2.2.7) lib/rack/conditional_get.rb:27:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | rack (2.2.7) lib/rack/head.rb:12:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | rack (2.2.7) lib/rack/session/abstract/id.rb:266:in `context'
17:13:34 web.1    | rack (2.2.7) lib/rack/session/abstract/id.rb:260:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/middleware/cookies.rb:689:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | activerecord (6.1.4.7) lib/active_record/migration.rb:601:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/callbacks.rb:98:in `run_callbacks'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/middleware/executor.rb:14:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | rollbar (3.4.0) lib/rollbar/middleware/rails/rollbar.rb:25:in `block in call'
17:13:34 web.1    | rollbar (3.4.0) lib/rollbar.rb:145:in `scoped'
17:13:34 web.1    | rollbar (3.4.0) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
17:13:34 web.1    | rollbar (3.4.0) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
17:13:34 web.1    | web-console (4.2.0) lib/web_console/middleware.rb:19:in `block in call'
17:13:34 web.1    | web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
17:13:34 web.1    | web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | railties (6.1.4.7) lib/rails/rack/logger.rb:37:in `call_app'
17:13:34 web.1    | railties (6.1.4.7) lib/rails/rack/logger.rb:26:in `block in call'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/tagged_logging.rb:99:in `block in tagged'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/tagged_logging.rb:37:in `tagged'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/tagged_logging.rb:99:in `tagged'
17:13:34 web.1    | railties (6.1.4.7) lib/rails/rack/logger.rb:26:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/middleware/request_id.rb:26:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | rack (2.2.7) lib/rack/method_override.rb:24:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | shopify_app (21.5.0) lib/shopify_app/middleware/jwt_middleware.rb:24:in `call_next'
17:13:34 web.1    | shopify_app (21.5.0) lib/shopify_app/middleware/jwt_middleware.rb:12:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | rack (2.2.7) lib/rack/runtime.rb:22:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | activesupport (6.1.4.7) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/middleware/executor.rb:14:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/middleware/static.rb:24:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | rack (2.2.7) lib/rack/sendfile.rb:110:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | actionpack (6.1.4.7) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | webpacker (4.3.0) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
17:13:34 web.1    | rack-proxy (0.7.6) lib/rack/proxy.rb:87:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | railties (6.1.4.7) lib/rails/engine.rb:539:in `call'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
17:13:34 web.1    | puma (4.3.12) lib/puma/configuration.rb:228:in `call'
17:13:34 web.1    | puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
17:13:34 web.1    | puma (4.3.12) lib/puma/server.rb:476:in `process_client'
17:13:34 web.1    | puma (4.3.12) lib/puma/server.rb:332:in `block in run'
17:13:34 web.1    | puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/tracer.rb:432:in `block (2 levels) in thread_block_with_current_transaction'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/tracer.rb:356:in `capture_segment_error'
17:13:34 web.1    | newrelic_rpm (9.0.0) lib/new_relic/agent/tracer.rb:431:in `block in thread_block_with_current_transaction'
```

**Comment by nelsonwittwer** [comment]
For that older version, I believe you'll need to add `config.shop_session_repository = "Shop"` where you'll substitue `Shop` with the name of your Shop model. Note, that in the most recent version of the API session storage is removed.

**Comment by CaioFML** [comment]
> For that older version, I believe you'll need to add `config.shop_session_repository = "Shop"` where you'll substitue `Shop` with the name of your Shop model. Note, that in the most recent version of the API session storage is removed.

I will try again, but I mentioned that I tried with `config.shop_session_repository = "Shop"` too and it didn't work, but maybe something was cached, let's see, I will update it soon here

**Comment by CaioFML** [comment]
@nelsonwittwer Sorry, I just could take back the upgrade right now!

So, the `config.shop_session_repository = "Shop"` I was using before the upgrade to the newest version, now in the ShopifyAPI::Context.setup, I tried the session_storage in this setup:

```ruby
    ShopifyAPI::Context.setup(
      ...
      session_storage: ShopifyApp::SessionRepository,
      ...
    )
```

Even using "Shop" there instead, it didn't work, any thoughts?

**Comment by CaioFML** [comment]
I think I found the issue, I create a new app from scratch with the newest version and I saw that we need to use both Shopify.configure and Shopify.setup, I was trying to do it with only Shopify.setup :)
