### ISSUE TITLE
Navigating from Shopify Admin into App page causes immediate reload

### ISSUE THREAD

**Issue by MauroVentosa** [Shopify/shopify_app#1849]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the package
  - `shopify_app` version:
  - Ruby version:
  - Operating system:
- [x] Set `log_level: :debug` [in my configuration](https://github.com/Shopify/shopify-api-ruby#setup-shopify-context), if applicable
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

## Expected behavior

Navigating to an App page should load the target page and not redirect to home. If there is an authentication error or any other error, it should be displayed either on the browser's console, or in the App logs.

## Actual behavior

Navigating to an App page from the Admin (Create Discounts menu) loads the desired view, then immediately gets redirected to home without a clear error. 

**This happens specifically after upgrading `shopify_app` to `22.2.0` or greater. The error goes away with version `22.1.0` or lower**

## Steps to reproduce the problem

1. Upgrade `shopify_app` to `22.2.0` or `22.2.1`
2. Navigate to Shopify Admin (Discounts admin)
3. Create new discount type that redirects into App page
4. Expected page loads and is visible, immediately gets redirected

## Debug logs

```
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | Started GET "/discounts/01cd81b7-e2c2-4621-8674-2173ff4db756/free_shipping
_on_monday_discounts/new?embedded=1&hmac=[REDACTED]&host=[REDACTED]&id_token=[FILTERED]&locale=en-US&session=[REDACTED]&shop=mejuri-staging-inc.myshopify.com&timestamp=1716213772" for 127.0.0.1 at 2024-05-20 11:02:53 -0300
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | Processing by Discounts::FreeShippingOnMondayDiscountsController#new as 
HTML
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Parameters: {"embedded"=>"1", 
"hmac"=>"[REDACTED]", 
"host"=>"[REDACTED]", "id_token"=>"[FILTERED]", "locale"=>"en-US", 
"session"=>"[REDACTED]", "shop"=>"mejuri-staging-inc.myshopify.com", 
"timestamp"=>"1716213772", "discount_id"=>"01cd81b7-e2c2-4621-8674-2173ff4db756"}
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Shop Load (2.4ms)  SELECT "shops".* FROM "shops" WHERE 
"shops"."shopify_domain" = $1 LIMIT $2  [["shopify_domain", "mejuri-staging-inc.myshopify.com"], ["LIMIT", 1]]
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | [ ShopifyApp | INFO | mejuri-staging-inc.myshopify.com ] Installed store  
- mejuri-staging-inc.myshopify.com deduced from user session
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   CACHE Shop Load (0.4ms)  SELECT "shops".* FROM "shops" WHERE 
"shops"."shopify_domain" = $1 LIMIT $2  [["shopify_domain", "mejuri-staging-inc.myshopify.com"], ["LIMIT", 1]]
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   ↳ app/controllers/concerns/current_shop.rb:17:in `current_shop'
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | [ ShopifyApp | INFO | mejuri-staging-inc.myshopify.com ] Installed store  
- mejuri-staging-inc.myshopify.com deduced from user session
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Rendering layout layouts/embedded_app.html.erb
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Rendering discounts/free_shipping_on_monday_discounts/new.html.erb 
within layouts/embedded_app
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Rendered discounts/_form.html.erb (Duration: 37.5ms | Allocations: 
17952)
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Rendered discounts/free_shipping_on_monday_discounts/new.html.erb within
 layouts/embedded_app (Duration: 67.9ms | Allocations: 29619)
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Rendered /Users/mauro.ventosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/
gems/hotwire-livereload-1.4.0/app/views/hotwire/livereload/_head_action_cable.html.erb (Duration: 0.3ms | Allocations: 222)
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Rendered layouts/_head.html.erb (Duration: 3.1ms | Allocations: 5887)
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Rendered layouts/_navigation_menu.html.erb (Duration: 0.6ms | 
Allocations: 596)
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Rendered layout layouts/embedded_app.html.erb (Duration: 76.1ms | 
Allocations: 38316)
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | Completed 200 OK in 247ms (Views: 78.1ms | ActiveRecord: 46.5ms | 
Allocations: 148445)
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | 
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | 
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | [ ShopifyApp | INFO | Shop Not Found ] Installed store  - 
mejuri-staging-inc.myshopify.com deduced from user session
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | Started GET "/cable" for 127.0.0.1 at 2024-05-20 11:02:53 -0300
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | Started GET "/home?shop=mejuri-staging-inc.myshopify.com" for 127.0.0.1 at
 2024-05-20 11:02:53 -0300
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | Started GET "/cable" [WebSocket] for 127.0.0.1 at 2024-05-20 11:02:53 
-0300
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: 
keep-alive, Upgrade, HTTP_UPGRADE: websocket)
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | Hotwire::Livereload::ReloadChannel is transmitting the subscription 
confirmation
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | Hotwire::Livereload::ReloadChannel is streaming from hotwire-reload
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | Processing by HomeController#show as HTML
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Parameters: {"shop"=>"mejuri-staging-inc.myshopify.com"}
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Shop Load (1.0ms)  SELECT "shops".* FROM "shops" WHERE 
"shops"."shopify_domain" = $1 LIMIT $2  [["shopify_domain", "mejuri-staging-inc.myshopify.com"], ["LIMIT", 1]]
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | [ ShopifyApp | INFO | mejuri-staging-inc.myshopify.com ] Installed store  
- mejuri-staging-inc.myshopify.com deduced from user session
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   CACHE Shop Load (0.4ms)  SELECT "shops".* FROM "shops" WHERE 
"shops"."shopify_domain" = $1 LIMIT $2  [["shopify_domain", "mejuri-staging-inc.myshopify.com"], ["LIMIT", 1]]
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   ↳ app/controllers/concerns/current_shop.rb:17:in `current_shop'
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | [ ShopifyApp | INFO | mejuri-staging-inc.myshopify.com ] Installed store  
- mejuri-staging-inc.myshopify.com deduced from user session
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Rendering layout layouts/embedded_app.html.erb
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Rendering home/show.html.erb within layouts/embedded_app
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Rendered home/show.html.erb within layouts/embedded_app (Duration: 
42.0ms | Allocations: 14375)
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Rendered /Users/mauro.ventosa/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/
gems/hotwire-livereload-1.4.0/app/views/hotwire/livereload/_head_action_cable.html.erb (Duration: 0.0ms | Allocations: 96)
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Rendered layouts/_head.html.erb (Duration: 0.5ms | Allocations: 829)
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Rendered layouts/_navigation_menu.html.erb (Duration: 0.2ms | 
Allocations: 249)
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  |   Rendered layout layouts/embedded_app.html.erb (Duration: 44.3ms | 
Allocations: 16405)
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | Completed 200 OK in 51ms (Views: 44.5ms | ActiveRecord: 0.5ms | 
Allocations: 19431)
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | 
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | 
11:02:53 │ web-frontend-backend │ 11:02:53 web.1  | [ ShopifyApp | INFO | Shop Not Found ] Installed store  - 
mejuri-staging-inc.myshopify.com deduced from user session
```

## Additional Info

I suspect either [this redirect](https://github.com/Shopify/shopify_app/commit/41282eaab44dee50c4ba32d7e1a2800161823437) introduced in `22.2.0` or the new [token exchange functionality](https://github.com/mejuri-inc/mejuri-central/pull/538), although it should be opt-in, and I've not enabled it.

**Comment by matteodepalo** [comment]
@MauroVentosa thank you for opening this issue, we're taking a look.

**Comment by resistorsoftware** [comment]
As a sample, here one can see the hit FROM Shopify Admin link to Product controller, it 500 errors out on purpose, but then successfully keeps on going to the Splash page, then back to the Product controller. Some kind of loop due to Auth tokens I suppose. 

```

Started GET "/product?embedded=1&hmac=2621c09fc3bfba13d792d0d718d6851e07525e0a6a560a2fa3482746f416491e&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvaG90d2lyZS1yZXNpc3Rvcg&id=7670628483327&id_token=[FILTERED]&locale=en&session=d520f279c4cec223aa30846cf8c4a36f897c1a218d4abcab234f7b8994fec86e&shop=hotwire-vodka.myshopify.com&timestamp=1716302062" for 69.157.235.200 at 2024-05-21 10:34:31 -0400
Cannot render console from 69.157.235.200! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by ProductsController#reprice as HTML
  Parameters: {"embedded"=>"1", "hmac"=>"2621c09fc3bfba13d792d0d718d6851e07525e0a6a560a2fa3482746f416491e", "host"=>"YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvaG90d2lyZS1yZXNpc4Rvcg", "id"=>"7670628483327", "id_token"=>"[FILTERED]", "locale"=>"en", "session"=>"d520f279c4cec223aa30846cf8c4a36f897c1a218d4abcab234f7b8994fec86e", "shop"=>"hotwire-vodka.myshopify.com", "timestamp"=>"1716302062"}
  [1m[36mShop Load (0.1ms)[0m  [1m[34mSELECT "shops".* FROM "shops" WHERE "shops"."shopify_domain" = $1 LIMIT $2[0m  [["shopify_domain", "hotwire-resistor.myshopify.com"], ["LIMIT", 1]]
  ↳ app/middleware/app_bridge_middleware.rb:13:in `call'
[ ShopifyApp | INFO | hotwire-vodka.myshopify.com ] Installed store  - hotwire-vodka.myshopify.com deduced from user session
[ ShopifyApp | INFO | hotwire-vodka.myshopify.com ] Installed store  - hotwire-vodka.myshopify.com deduced from user session
  [1m[36mCACHE Shop Load (0.0ms)[0m  [1m[34mSELECT "shops".* FROM "shops" WHERE "shops"."shopify_domain" = $1 LIMIT $2[0m  [["shopify_domain", "hotwire-resistor.myshopify.com"], ["LIMIT", 1]]
  ↳ app/controllers/authenticated_controller.rb:15:in `current_shop'
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.1ms | Allocations: 2454)
  
NameError (uninitialized constant ProductsController::Raill):
  
app/controllers/products_controller.rb:7:in `reprice'
app/middleware/app_bridge_middleware.rb:13:in `call'
Started GET "/cable" for 69.157.235.200 at 2024-05-21 10:34:32 -0400
Cannot render console from 69.157.235.200! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Started GET "/cable" [WebSocket] for 69.157.235.200 at 2024-05-21 10:34:32 -0400
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable" [WebSocket] for 69.157.235.200 at 2024-05-21 10:34:32 -0400
Started GET "/product?embedded=1&hmac=2621c09fc3bfba13d792d0d718d6851e07525e0a6a560a2fa3482746f416491e&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvaG90d2lyZS1yZXNpc4Rvcg&id=7670628483327&id_token=[FILTERED]&locale=en&session=d520f279c4cec223aa30846cf8c4a36f897c1a218d4abcab234f7b8994fec86e&shop=hotwire-vodka.myshopify.com&timestamp=1716302062" for 69.157.235.200 at 2024-05-21 10:34:32 -0400
Cannot render console from 69.157.235.200! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by ProductsController#reprice as HTML
  Parameters: {"embedded"=>"1", "hmac"=>"2621c09fc3bfba13d792d0d718d6851e07525e0a6a560a2fa3482746f416491e", "host"=>"YWRtaW4uc2hvcGlmeS5jb20vc4RvcmUvaG90d2lyZS1yZXNpc3Rvcg", "id"=>"7670628483327", "id_token"=>"[FILTERED]", "locale"=>"en", "session"=>"d520f279c4cec223aa30846cf8c4a36f897c1a218d4abcab234f7b8994fec86e", "shop"=>"hotwire-vodka.myshopify.com", "timestamp"=>"1716302062"}
[ ShopifyApp | INFO | Shop Not Found ] Installed store  - hotwire-vodka.myshopify.com deduced from user session
Redirected to https://vodkatonic.ngrok.io/?embedded=1&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvaG90d2lyZS1yZXNpc3Rvcg&return_to=%2Fproduct%3Fembedded%3D1%26hmac%3D2621c09fc3bfba13d792d0d718d6851e07525e0a6a560a2fa3482746f416491e%26host%3DYWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvaG90d2lyZS1yZXNpc4Rvcg%26id%3D7670628483327%26id_token%3DeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVDJ9.eyJpc3MiOiJodHRwczpcL1wvaG90d2lyZS1yZXNpc3Rvci5teXNob3BpZnkuY29tXC9hZG1pbiIsImRlc3QiOiJodHRwczpcL1wvaG90d2lyZS1yZXNpc3Rvci5teXNob3BpZnkuY29tIiwiYXVkIjoiNmE1YjIzMTc1NjA4OGQ1NjY5ZjdhMmIxMjhmNzliZTIiLCJzdWIiOiI3OTM4MjAyMDM1MSIsImV4cCI6MTcxNjMwMjEyMiwibmJmIjoxNfE2MzAyMDYyLCJpYXQiOjE3MTYzMDIwNjIsImp0aSI6ImY0MjU0MDEzLWYwMjUtNGM4MC1hMTdhLTk5ZjFkMjE5MmNmMiIsInNpZCI6IjBmOTZiNDI0LWIzZDMtNGFkMC1hZTc4LWZhN2Y1NmE4NmU5NyIsInNpZyI6ImM4MWI3YmE2MDRlNDk2NjYxMmZjZDAzYTQ3M2MzZTJhYzBjZGM5YTJhYmM3YmUzMDViYTUxYzg4NWU1NzYwYTQifQ.ICcfKS7YjhkW2FCxs8_BU3a9ikXBl1GbUNxUSaxO1fY%26locale%3Den%26session%3Dd520f279c4cec223aa30846cf8c4a36f897c1a218d4abcab234f7b8994fec86e%26shop%3Dhotwire-vodka.myshopify.com%26timestamp%3D1716302062&shop=hotwire-vodka.myshopify.com
Filter chain halted as :redirect_to_splash_page rendered or redirected
Completed 302 Found in 1ms (ActiveRecord: 0.0ms | Allocations: 449)

```

From here, the Splash Page controller that rendered at the root checks for the return_to param, and heads on back to Product, thus looping!!

**Comment by resistorsoftware** [comment]
I updated to Shopify App 22.2.1 and can confirm. For no apparently clear reason, when an ADMIN LINK from Shopify hits the App, the router executes the controller and completes fine, but the App then redirects to the HOME PAGE!!! 

WOW. I am trying to debug this, but with the logs all clean, it'll take a few debug steps to isolate where this is happening!

**Comment by MauroVentosa** [comment]
Hi @matteodepalo any updates on this issue??

**Comment by resistorsoftware** [comment]
@uurcank Sure. 

```
class SplashPageController < ApplicationController
  include ShopifyApp::EmbeddedApp
  include ShopifyApp::EnsureInstalled
  include ShopifyApp::ShopAccessScopesVerification

  def index
    shop = Shop.find_by!(shopify_domain: current_shopify_domain)
    shop.save_host(params[:host])
    @host = shop.host
    @shop_origin = current_shopify_domain
  end
end

```

Ok.. fine.. so authenticated means checking for JWT tokens and the like... 

```
class AuthenticatedController < ApplicationController
  include ShopifyApp::EnsureAuthenticatedLinks
  include ShopifyApp::EnsureHasSession

  skip_before_action :redirect_to_splash_page, unless: -> { Rails.configuration.force_iframe }

  before_action :set_shop_origin
  before_action :set_host

  helper_method :current_shop, :jwt_expire_at

  def current_shop
    @current_shop ||= Shop.find_by(shopify_domain: current_shopify_domain)
  end

  def default_url_options
    {shop: @shop_origin}
  end

  def fullpage_redirect_to(url)
    super(url)
    response.status = 303
  end

  private

  def set_shop_origin
    @shop_origin = current_shopify_domain
  end

  def set_host
    params[:host] = current_shop.host
    @host = params[:host]
  end

  def turbo_flashes
    turbo_stream.replace("shopify-app-flash", partial: "layouts/flash_messages.html.erb")
  end
end

```

**Comment by uurcank** [comment]
Can you delete skip_before_action and try again? 

With token exchange it should not be necessary.
