### ISSUE TITLE
GemRequireError when executing 'rails generate shopify_app' or 'rails server'

### ISSUE THREAD

**Issue by triskybro** [Shopify/shopify_app#211]
Following the installation instructions on the Readme.md resulted in the error below.

If I comment out `Bundler.require(*Rails.groups)` in application.rb, the command executes, but this is not a viable workaround. 

```
/usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in
rescue in block (2 levels) in require': There was an error while trying to load the gem 'shopify_app'. (Bundler::GemRequireError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /Users/<user name>/Development/odd1/config/application.rb:7:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/application.rb:82:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/application.rb:82:in `preload'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/application.rb:143:in `serve'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/application.rb:131:in `block in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/application.rb:125:in `loop'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/application.rb:125:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/spring-1.6.2/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by kevinhughes27** [comment]
Can you try again with running `spring stop` before? I need more details in order to help you out here - what ruby and bundler version? Can you also post your gemfile please

**Comment by triskybro** [comment]
Stopping Spring didnt' help.

Ruby Version:
```
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
```

Bundler Version
```
$ bundle -v
Bundler version 1.11.2
```

Gemfile:
```
source 'https://rubygems.org'

gem 'rails', '4.1.6'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development

gem 'shopify_app'

```

**Comment by triskybro** [comment]
I just tried version 6.0.6 and was able to run both `rails server` and `rails generate shopify_app` successfully

`gem 'shopify_app', '~> 6.0.6'`

**Comment by kevinhughes27** [comment]
sounds like there may be an issue with the latest release
cc @gmalette

**Comment by gmalette** [comment]
@kevinhughes27 
I bisected and it seems the problematic commit is 46f6ed767083390a1681b654636b60ddc84b39bf
That's probably a bug that was fixed, because the actual original problem started with 89d41d9a01071112c194e12d44a9013673fbd71c, with the introduction of `ActiveJob`, but without bumping the Rails dependency to 4.2

**Comment by kevinhughes27** [comment]
ahh that makes sense (too bad the original bundler message wasn't more helpful). ActiveJob can be used in earlier versions of rails if its included manually or we can just add the dependency of rails 4.2. I can look into fixing this tomorrow
