### ISSUE TITLE
Directly inheriting from ActiveRecord::Migration is not supported

### ISSUE THREAD

**Issue by StraubCreative** [Shopify/shopify_app#410]
I'm trying to run
`rake db:migrate`

...and I get the following error

```
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateShops < ActiveRecord::Migration[4.2]
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:525:in `inherited'
/Users/zacharystraub/github/pixel-wizard/db/migrate/20170502090059_create_shops.rb:1:in `<top (required)>'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:962:in `load_migration'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:958:in `migration'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:953:in `disable_ddl_transaction'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1305:in `use_transaction?'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1297:in `ddl_transaction'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1200:in `each'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1148:in `block in migrate'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1148:in `migrate'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1007:in `up'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:985:in `migrate'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateShops < ActiveRecord::Migration[4.2]
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:525:in `inherited'
/Users/zacharystraub/github/pixel-wizard/db/migrate/20170502090059_create_shops.rb:1:in `<top (required)>'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:962:in `load_migration'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:958:in `migration'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:953:in `disable_ddl_transaction'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1305:in `use_transaction?'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1297:in `ddl_transaction'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1200:in `each'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1148:in `block in migrate'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1148:in `migrate'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:1007:in `up'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/migration.rb:985:in `migrate'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/activerecord-5.1.0/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/zacharystraub/.rvm/gems/ruby-2.2.4/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

I've attempted to modify the activeresource gem to specify `ActiveRecord::Migration` version however there is no `class CreateShops` in the file.

Something I'm missing?

**Comment by StraubCreative** [comment]
Fixed.
Went to db/migrate/<id>_create_shops.rb
and changed `class CreateShops < ActiveRecord::Migration` to 'class CreateShops < ActiveRecord::Migration[4.2]'

**Comment by kevinhughes27** [comment]
Want to submit a PR for the fix? feels like the template should be updated :smile:
