### ISSUE TITLE
Could not create an AfterAuthenticateJob

### ISSUE THREAD

**Issue by ncpope** [Shopify/shopify_app#481]
I have been unable to get the rails generate the skeleton job successfully. I have tried the auto generator available through shopify_app both on an existing project and a freshly installed project with no luck.

I ran into this error following the instructions at: https://github.com/Shopify/shopify_app#afterauthenticate-job

```
$ bin/rails g shopify_app:add_after_authenticate_job
Running via Spring preloader in process 12223
Could not find generator 'shopify_app:add_after_authenticate_job'. Maybe you meant 'shopify_app:add_webhook', 'shopify_app:app_proxy_controller' or 'shopify_app:home_controller'
Run `rails generate --help` for more options.
```

When I manually add the job to config/initializers/shopify_app.rb I receive the following error afterwards:

```
rails g model NewModel
/Users/nathan/Documents/shopify_app_test/config/initializers/shopify_app.rb:7:in `block in <top (required)>': uninitialized constant Shopify (NameError)
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/shopify_app-7.2.11/lib/shopify_app/configuration.rb:53:in `configure'
	from /Users/nathan/Documents/shopify_app_test/config/initializers/shopify_app.rb:1:in `<top (required)>'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/engine.rb:655:in `block in load_config_initializer'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/engine.rb:654:in `load_config_initializer'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/engine.rb:611:in `each'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /Users/nathan/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /Users/nathan/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/nathan/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/nathan/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/nathan/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `each'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `tsort_each_child'
	from /Users/nathan/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:415:in `call'
	from /Users/nathan/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/nathan/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/nathan/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /Users/nathan/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /Users/nathan/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/nathan/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /Users/nathan/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
	from /Users/nathan/Documents/shopify_app_test/config/environment.rb:5:in `<top (required)>'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:102:in `require'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/nathan/.rvm/gems/ruby-2.4.1/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/nathan/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/nathan/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

Ruby and Rails versions:

```
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
$ rails -v 
Rails 5.1.4
```

**Comment by kevinhughes27** [comment]
what version of the gem are you using? please make sure you are using the latest release

**Comment by ncpope** [comment]
Thanks that was it. I saw that support for the generator was added in 7.4.0 and I was running an earlier version.

If anyone else experiences this issue I was able to resolve this by adding the line `gem 'shopify_app', '~> 8.2'`to my gemfile and running `bundle install`
