### ISSUE TITLE
Rails app crashes after gem updating / setting up webhooks

### ISSUE THREAD

**Issue by AnatolZaitsev** [Shopify/shopify_app#530]
First of all, I have a problem with webhooks configuration.
```
  config.webhooks = [
    { topic: 'carts/create',     address: "#{configus.app_url}webhooks/discounts_applying", fields: %w(id line_items) },
    { topic: 'carts/update',     address: "#{configus.app_url}webhooks/discounts_applying", fields: %w(id line_items) },
    { topic: 'checkouts/create', address: "#{configus.app_url}webhooks/discounts_applying", fields: %w(id token cart_token discount_codes customer) },
    { topic: 'checkouts/update', address: "#{configus.app_url}webhooks/discounts_applying", fields: %w(id token cart_token discount_codes customer) }
]
```

It was no effect and I tryed to add any webhook manually:
```
rails g shopify_app:add_webhook -t checkouts/update -a https://my_application_url.com/webhooks/discounts_applying
```
And there were no configured webhooks despite on command executed without errors(checked with ```ShopifyAPI::Webhook.find(:all)``` with active Shopify session).

There was proposed to update gem in another issue tagged with webhooks.
So, it was done and when I try to do ```rails s```, I get this:
```
/Users/Anatol_Zaitsev/Documents/work/evrone/projects/bloomperfumery/bloomperfumery_app/app/models/shop.rb:2:in `<class:Shop>': uninitialized constant ShopifyApp::Shop (NameError)
        from /Users/Anatol_Zaitsev/Documents/work/evrone/projects/bloomperfumery/bloomperfumery_app/app/models/shop.rb:1:in `<top (required)>'
        from /Users/Anatol_Zaitsev/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
        from /Users/Anatol_Zaitsev/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
        from /Users/Anatol_Zaitsev/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:11:in `loading'
        from /Users/Anatol_Zaitsev/Documents/work/evrone/projects/bloomperfumery/bloomperfumery_app/config/initializers/shopify_session_repository.rb:7:in `block in <top (required)>'
```

**Comment by AnatolZaitsev** [comment]
8.2.4 – the same error

**Comment by kevinhughes27** [comment]
Just to follow up on the issue - the Shop concern was deprecated and removed in version 8.
