### ISSUE TITLE
There was an error while trying to load the gem 'shopify_app'. (Bundler::GemRequireError). Gem Load Error is: undefined method `alias_method_chain' for ActiveResource::Base:Class

### ISSUE THREAD

**Issue by mur-wtag** [Shopify/shopify_app#532]
Environment
-----------------

Ruby version: `2.3.1`
Bundler version: `1.16.0`
Rails Version: `5.1.4`
Shopify App version: `8.2.5`

Error Log
---------------------

```
Mac-mini:cool-app rony36$ rails s -p 3000
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/bundler-1.16.0/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'shopify_app'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `alias_method_chain' for ActiveResource::Base:Class
Did you mean?  alias_method
Backtrace for gem load error is:
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/bundler/gems/activeresource-759ded7490cb/lib/active_resource/validations.rb:103:in `block in <module:Validations>'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/activesupport-5.1.4/lib/active_support/concern.rb:120:in `class_eval'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/activesupport-5.1.4/lib/active_support/concern.rb:120:in `append_features'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/bundler/gems/activeresource-759ded7490cb/lib/active_resource/base.rb:1561:in `include'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/bundler/gems/activeresource-759ded7490cb/lib/active_resource/base.rb:1561:in `<class:Base>'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/bundler/gems/activeresource-759ded7490cb/lib/active_resource/base.rb:1557:in `<module:ActiveResource>'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/bundler/gems/activeresource-759ded7490cb/lib/active_resource/base.rb:23:in `<top (required)>'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/shopify_api-4.9.0/lib/active_resource/json_errors.rb:1:in `require'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/shopify_api-4.9.0/lib/active_resource/json_errors.rb:1:in `<top (required)>'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/shopify_api-4.9.0/lib/shopify_api.rb:10:in `require'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/shopify_api-4.9.0/lib/shopify_api.rb:10:in `<top (required)>'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/shopify_app-8.2.5/lib/shopify_app.rb:4:in `require'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/shopify_app-8.2.5/lib/shopify_app.rb:4:in `<top (required)>'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:in `require'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `each'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `block in require'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `each'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `require'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/bundler-1.16.0/lib/bundler.rb:114:in `require'
/Users/rony36/Source Code/sqr/github/cool-app/config/application.rb:7:in `<top (required)>'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `require'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `block in perform'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
/Users/rony36/Source Code/sqr/github/cool-app/bin/rails:9:in `require'
/Users/rony36/Source Code/sqr/github/cool-app/bin/rails:9:in `<top (required)>'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/Users/rony36/Source Code/sqr/github/cool-app/bin/spring:13:in `require'
/Users/rony36/Source Code/sqr/github/cool-app/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Bundler Error Backtrace:
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/bundler-1.16.0/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `each'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `block in require'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `each'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `require'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/bundler-1.16.0/lib/bundler.rb:114:in `require'
        from /Users/rony36/Source Code/sqr/github/cool-app/config/application.rb:7:in `<top (required)>'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `require'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:133:in `block in perform'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
        from /Users/rony36/Source Code/sqr/github/cool-app/bin/rails:9:in `require'
        from /Users/rony36/Source Code/sqr/github/cool-app/bin/rails:9:in `<top (required)>'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
        from /Users/rony36/.rvm/gems/ruby-2.3.1@coolapp/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
        from /Users/rony36/Source Code/sqr/github/cool-app/bin/spring:13:in `require'
        from /Users/rony36/Source Code/sqr/github/cool-app/bin/spring:13:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
```

**Comment by kevinhughes27** [comment]
This exception is actually coming from the shopify_api gem when it is requiring active_resource. What version of active resource are you using? Try updating it.

**Comment by mur-wtag** [comment]
wow, yes it's working by upgrading `activeresource` with version `activeresource (~> 5.0.0)`.
Thanks!

**Comment by smcalilly** [comment]
I get a similar error after running `rails generate shopify_app ` with Ruby 2.6.3 and Rails 6.0.0.rc1.


```
~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shopify_api-4.2.2/lib/active_resource/connection_ext.rb:28:in 
`<class:Connection>': undefined method `alias_method_chain' for ActiveResource::Connection:Class
Did you mean?  alias_method (NoMethodError)
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shopify_api-4.2.2/lib/active_resource/connection_ext.rb:4:in `<module:ActiveResource>'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shopify_api-4.2.2/lib/active_resource/connection_ext.rb:3:in `<main>'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shopify_api-4.2.2/lib/shopify_api.rb:7:in `<main>'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shopify_app-7.0.11/lib/shopify_app.rb:4:in `<main>'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler.rb:114:in `require'
	from /Users/samuel/Desktop/test-app/config/application.rb:7:in `<top (required)>'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:92:in `require'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:92:in `preload'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

```

**Comment by smcalilly** [comment]
I ran `bundle exec rake -P --trace` and got this:

```
rake aborted!
NoMethodError: undefined method `alias_method_chain' for ActiveResource::Connection:Class
Did you mean?  alias_method
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shopify_api-4.2.2/lib/active_resource/connection_ext.rb:28:in `<class:Connection>'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shopify_api-4.2.2/lib/active_resource/connection_ext.rb:4:in `<module:ActiveResource>'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shopify_api-4.2.2/lib/active_resource/connection_ext.rb:3:in `<main>'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shopify_api-4.2.2/lib/shopify_api.rb:7:in `<main>'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `block in require'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:302:in `require'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/shopify_app-7.0.11/lib/shopify_app.rb:4:in `<main>'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/runtime.rb:76:in `each'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/runtime.rb:65:in `each'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/runtime.rb:65:in `require'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler.rb:114:in `require'
/Users/samuel/Desktop/test-app/config/application.rb:7:in `<top (required)>'
/Users/samuel/Desktop/test-app/Rakefile:4:in `require_relative'
/Users/samuel/Desktop/test-app/Rakefile:4:in `<top (required)>'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load_rakefile'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:703:in `raw_load_rakefile'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:104:in `block in load_rakefile'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:103:in `load_rakefile'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:82:in `block in run'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/samuel/.rbenv/versions/2.6.3/bin/rake:23:in `load'
/Users/samuel/.rbenv/versions/2.6.3/bin/rake:23:in `<top (required)>'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/samuel/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/Users/samuel/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
/Users/samuel/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'
```

**Comment by azzouzze** [comment]
any suggestion to pass the issue and get the app generated ?

**Comment by smcalilly** [comment]
i haven't figured it out yet. have you tried with other versions of rails?

**Comment by azzouzze** [comment]
what s the official stack requirement ?
