### ISSUE TITLE
Shopify SSL callbacks failing

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#612]
Fired up latest Shopify App with Rails 5.2 and Rubies 2.4.2 and 2.5.1 on two projects..

Latest issue have never seen, and it is a blocker... Am using **forward** to send myawsomeapp.test to my locahost, a service that is for sure sweet and works. Am using latest puma-dev to serve up Rails App with Puma and https.

So I call the login screen, end up at https://myawesomeapp.test/login with all things in order. App accepts store name, and sends oAuth request to shopify. Store then shows me App scopes, and whether to install or not. I click YES, and then this SSL error kicks in from all Apps, all Rubies, and has me wondering what might have changed with Shopify all of a sudden?

Started POST "/login" for 127.0.0.1 at 2018-07-17 22:17:18 -0400
Processing by ShopifyApp::SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"fgstsRztxEIsbu3GvP70ZFmYLEKYpr0o1BVQldHatlOkzpYyQVDiYjd9dQlg1GH44OfhVDwofs3xtsTJyADp4w==", "shop"=>"swift-braun3430.myshopify.com"}
  Rendering /Users/dlazar/.rvm/gems/ruby-2.4.2/gems/shopify_app-8.2.6/app/views/shopify_app/shared/redirect.html.erb
  Rendered /Users/dlazar/.rvm/gems/ruby-2.4.2/gems/shopify_app-8.2.6/app/views/shopify_app/shared/redirect.html.erb (1247.7ms)
Completed 200 OK in 1261ms (Views: 1257.4ms | ActiveRecord: 0.0ms)

Started GET "/auth/shopify" for 127.0.0.1 at 2018-07-17 22:17:19 -0400
I, [2018-07-17T22:17:19.606206 #14630]  INFO -- omniauth: (shopify) Setup endpoint detected, running now.
I, [2018-07-17T22:17:19.606501 #14630]  INFO -- omniauth: (shopify) Request phase initiated.
Started GET "/auth/shopify/callback?code=d79e51f4e6ed5b6742fcbe55f0d580bd&hmac=9c382ed39cbdac74f04bdf3ad336096fed29391975daae831ac704996bd7841a&shop=swift-braun3430.myshopify.com&state=633d42284eab6b650ed1afeb9cf4fe143df90eef190f622b&timestamp=1531880243" for 127.0.0.1 at 2018-07-17 22:17:23 -0400
I, [2018-07-17T22:17:23.467195 #14630]  INFO -- omniauth: (shopify) Setup endpoint detected, running now.
I, [2018-07-17T22:17:23.467557 #14630]  INFO -- omniauth: (shopify) Callback phase initiated.

    Faraday::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed):

/Users/dlazar/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock'
/Users/dlazar/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
/Users/dlazar/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http.rb:948:in `connect'
/Users/dlazar/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/Users/dlazar/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http.rb:876:in `start'
/Users/dlazar/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/net/http.rb:1407:in `request'

**Comment by resistorsoftware** [comment]
Never mind. Turned out the Puma Dev CA certificate was not pinned to the CA chain openSSL was using, so I had to manually do that. Once done, things worked again.
