### ISSUE TITLE
rails generate shopify_app deprecated functions

### ISSUE THREAD

**Issue by azzouzze** [Shopify/shopify_app#755]
getting the following issues when generating the app:

```
/.rvm/gems/ruby-2.6.3/gems/activesupport-4.1.4/lib/active_support/core_ext/object/duplicable.rb:82: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
/.rvm/gems/ruby-2.6.3/gems/activesupport 4.1.4/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/.rvm/gems/ruby-2.6.3/gems/activesupport-4.1.4/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
Traceback (most recent call last):
	8077: from bin/rails:4:in `<main>'
	8076: from bin/rails:4:in `require'
	8075: from /.rvm/gems/ruby-2.6.3/gems/railties-4.1.4/lib/rails/commands.rb:17:in `<top (required)>'
	8074: from /.rvm/gems/ruby-2.6.3/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	8073: from /.rvm/gems/ruby-2.6.3/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:51:in `generate'
	8072: from /.rvm/gems/ruby-2.6.3/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:133:in `generate_or_destroy'
	8071: from /.rvm/gems/ruby-2.6.3/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:147:in `require_application_and_environment!'
	8070: from /.rvm/gems/ruby-2.6.3/gems/railties-4.1.4/lib/rails/application.rb:276:in `require_environment!'
	 ... 8065 levels...
	   4: from /.rvm/gems/ruby-2.6.3/gems/activesupport-4.1.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	   3: from /.rvm/gems/ruby-2.6.3/gems/activesupport-4.1.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	   2: from /.rvm/gems/ruby-2.6.3/gems/activesupport-4.1.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	   1: from /.rvm/gems/ruby-2.6.3/gems/activesupport-4.1.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
/.rvm/gems/ruby-2.6.3/gems/activesupport-4.1.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>': stack level too deep (SystemStackError)
```

**Comment by nwtn** [comment]
Thanks for the heads-up. It looks like this actually breaking generation for you. Is that right, or are these just warnings?

**Comment by azzouzze** [comment]
it s right. It does not generate. it seems to be related to the ruby version and deprecated functions.
any suggestion ?

**Comment by smcalilly** [comment]
I'm having some similar issues I think, after generating the app. I just commented on a closed issue: https://github.com/Shopify/shopify_app/issues/532#issuecomment-498931905

**Comment by smcalilly** [comment]
@nwtn any idea what's going on? i'm still blocked because of this. is this a rails issue or shopfiy_app gem issue?

**Comment by azzouzze** [comment]
what s the latest stack version validated?

**Comment by tanema** [comment]
This was actually an issue with rails and has since been fixed
