### ISSUE TITLE
NoMethodError in rails 3.2.13

### ISSUE THREAD

**Issue by maxrice** [Shopify/shopify_app#78]
The fix for #70 implemented in #71 breaks shopify_app in rails 3.2.13 with a NoMethodError. Changing it back to `before_configuration` solves the issue. redacted trace from our app:

```
/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/railtie/configuration.rb:85:in `method_missing': undefined method `shopify' for #<Rails::Application::Configuration:0x007fb8dc368ef8> (NoMethodError)
from /app/config/application.rb:16:in `<class:Application>'
from /app/config/application.rb:13:in `<module:App>'
from /app/config/application.rb:12:in `<top (required)>'
from /.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:53:in `require'
from /.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:53:in `block in <top (required)>'
from /.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:50:in `tap'
from /.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/railties-3.2.13/lib/rails/commands.rb:50:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>'
```

**Comment by kevinhughes27** [comment]
this is for the old generator. closing
